=== rdwz/linksapp-fresh/profile.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Profile",
  "description": "Profile configuration properties",
  "type": "object",
  "properties": {
    "avatar": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https)://"
    },
    "username": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50
    },
    "bio": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "location": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "readme": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https)://(.*)(\\.md)$"
    },
    "socialAccounts": {
      "type": "object",
      "properties": {
        "buymeacoffee": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://(www.)?buymeacoffee.com/"
        },
        "dribbble": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://(www.)?dribbble.com/"
        },
        "facebook": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://(www.)?facebook.com/"
        },
        "github": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://(www.)?github.com/"
        },
        "instagram": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://(www.)?instagram.com/"
        },
        "linkedin": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://(www.)?linkedin.com/in/"
        },
        "twitter": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://(www.)?twitter.com/"
        },
        "youtube": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://(www.)?youtube.com/"
        },
        "website": {
          "type": "string",
          "format": "uri",
          "pattern": "^(https)://"
        },
        "mail": {
          "type": "string",
          "format": "email"
        }
      }
    },
    "banner": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 50
        },
        "text": {
          "type": "string",
          "minLength": 1,
          "maxLength": 128
        }
      },
      "required": [
        "title",
        "text"
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "format": "uri",
            "pattern": "^(https)://"
          },
          "title": {
            "type": "string",
            "minLength": 1,
            "maxLength": 50
          }
        },
        "required": [
          "url",
          "title"
        ]
      },
      "minItems": 1
    },
    "rss": {
      "type": "string",
      "format": "uri",
      "pattern": "^(https)://"
    }
  },
  "required": [
    "avatar",
    "username",
    "links",
    "bio",
    "socialAccounts"
  ]
}

=== rdwz/linksapp-fresh/profile.json
{
  "$schema": "./profile.schema.json",
  "avatar": "https://seccdn.libravatar.org/avatar/7c97a040c62229f18e72f0e4581b0334?s=192",
  "username": "Marc Redwerkz",
  "links": [
    { "url": "https://rdwz.one", "title": "rdwz.one" },
    { "url": "https://digital-ra.in", "title": "digital-ra.in" },
    { "url": "https://modus.bio", "title": "modus.bio" }
  ],
  "bio": "Freigeist / Polymath",
  "location": "Cologne, Germany",
  "socialAccounts": {
    "buymeacoffee": "https://buymeacoffee.com/rdwz",
    "dribbble": "https://dribbble.com/rdwz",
    "github": "https://github.com/rdwz",
    "youtube": "https://www.youtube.com/@rdwz"
  },
  "banner": {
    "title": "Photo book release!",
    "text": "You can now order my newly released photobook."
  },
  "rss": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
  "readme": "https://raw.githubusercontent.com/rdwz/linksapp-fresh/main/README.md"
}
